### ISSUE TITLE
Error in CH04-Session/HttpServerSession.md

### ISSUE THREAD

**Issue by hankai17** [oknet/atsinternals#14]
在 HttpSM::tunnel_handler_server 中会进行如下的判断：

如果已经收到了 EOS 事件，
那么就调用 HttpServerSession::do_io_close 关闭。
如果不允许 OServer 的连接复用，
那么就调用 HttpClientSession::attach_server_session 把 HttpServerSession 附到 HttpClientSession 上。
如果允许连接复用，
设置 keep alive 超时时间，然后调用 HttpServerSession::release 与 HttpSM 脱离

**Comment by oknet** [comment]
请问这里有什么问题？

**Comment by hankai17** [comment]
```
if (t_state.txn_conf->attach_server_session_to_client == 1 && ua_session && t_state.client_info.keep_alive == HTTP_KEEPALIVE) {
      Debug("http", "attaching server session to the client");
      ua_session->attach_server_session(server_session);
    } else {
      // Release the session back into the shared session pool
      server_session->get_netvc()->set_inactivity_timeout(HRTIME_SECONDS(t_state.txn_conf->keep_alive_no_activity_timeout_out));
      server_session->release();
    }
```
应该是
如果允许 OServer 的连接复用，
那么就调用 HttpClientSession::attach_server_session 把 HttpServerSession 附到 HttpClientSession 上。
如果不允许连接复用，
设置 keep alive 超时时间，然后调用 HttpServerSession::release 与 HttpSM 脱离

**Comment by oknet** [comment]
感谢指正，这里我修改一下。

**Comment by oknet** [comment]
Fixed by PR #16 .
